import os
import re
from pathlib import Path

cpu_name = 'I8086'

root = Path(__file__).parents[1]
cpu_root = os.path.join(root, 'chips', cpu_name)
cpu_include_root = os.path.join(cpu_root, 'inc', cpu_name)

read_target = os.path.join(cpu_include_root, f'{cpu_name}_OpCodes.h')
write_target = os.path.join(cpu_include_root, f'{cpu_name}_OpCodesList.h')
instructions_target = os.path.join(cpu_root, 'INSTRUCTIONS.MD')

def scan_regex(path, re_exp, callback):
    with open(path, 'r') as file:
        re_instance = re.compile(re_exp)
        for line in file.readlines():
            re_res = re_instance.search(line)
            if re_res:
                callback(re_res)

opcodes_list = []
opcode_re_exp = r'\[x\]\s+(\w+).*$'  # [x] INSTRUCTION_NAME
scan_regex(instructions_target, opcode_re_exp, lambda x: opcodes_list.append(x.group(1)))

op_map = dict()
opcode_re_exp = r'\s+([\w]+)\s+=\s+(0[xX][0-9a-fA-F]+)'  # INSTRUCTION_NAME = 0xAE
scan_regex(read_target, opcode_re_exp, lambda x: op_map.update({x.group(1): int(x.group(2), 16)}))

ops = ['ADD_CALL(INVALID_OP)'] * 256

used_instructions = 0
for i in op_map:
    if any(i.startswith(item) for item in opcodes_list):
        ops[op_map[i]] = f'ADD_CALL({i})'
        used_instructions += 1

print(f"Used instructions: {used_instructions}/{len(op_map.keys())}")

ops_strings = []
align_len = max(map(len, ops)) + 3
while ops:
    row = ops[:5]
    ops = ops[5:]
    row_str = [(op + ',').ljust(align_len) for op in row]
    ops_strings.append(''.join(row_str))

disclaimer_string = '''//##############################################################################
// This is a lookup table entries generated by tools/code_gen.py
// Please don't edit
//##############################################################################

'''

with open(write_target, 'w') as out_file:
    out_file.writelines(disclaimer_string + '\n'.join(ops_strings))
