import os
import re

cpu_name = 'I8086'

script_path = __file__
parent = os.path.split(__file__)[0]
root = os.path.split(parent)[0]

read_target = os.path.join(os.path.join(root, f'chips'), cpu_name, 'inc', cpu_name, f'{cpu_name}_OpCodes.h')
write_target = os.path.join(os.path.join(root, f'chips'), cpu_name, 'inc', cpu_name, f'{cpu_name}_OpCodesList.h')
instructions_target = os.path.join(os.path.join(root, f'chips'), cpu_name, f'INSTRUCTIONS.MD')

opcodes_list = []
with open(instructions_target, 'r') as file:
    lines = file.readlines()
    opcode_exp = r'\[x\]\s+(\w+).*$'  # [x] INSTRUCTION_NAME
    opcode_re = re.compile(opcode_exp)
    for line in lines:
        re_res = opcode_re.search(line)
        if re_res:
            opcodes_list.append(re_res.group(1))

op_map = dict()
with open(read_target, 'r') as file:
    data = [i for i in file.readlines() if '=' in i]
    opcode_exp = r'\s+([\w]+)\s+=\s+(0[xX][0-9a-fA-F]+)'  # INSTRUCTION_NAME = 0xAE
    opcode_re = re.compile(opcode_exp)
    for i in data:
        re_res = opcode_re.search(i)
        if re_res:
            op_map[re_res.group(1)] = int(re_res.group(2), 16)

ops = ['ADD_CALL(INVALID_OP)'] * 256

used_instructions = 0
for i in op_map:
    if any(i.startswith(item) for item in opcodes_list):
        ops[op_map[i]] = f'ADD_CALL({i})'
        used_instructions += 1

print(f"Used instructions: {used_instructions}/{len(op_map.keys())}")

ops_strings = []
while ops:
    line = ops[:5]
    ops = ops[5:]
    line_str = []
    for i in line:
        line_str.append((str(i) + ',').ljust(25))
    res = ''.join(line_str)
    ops_strings.append(res)

ops_strings = '\n'.join(ops_strings)
disclaimer_string = '''//##############################################################################
// This is a lookup table entries generated by tools/code_gen.py
// Please don't edit
//##############################################################################

'''
ops_strings = disclaimer_string + ops_strings

with open(write_target, 'w') as file:
    file.writelines(ops_strings)
